services:
  - type: web
    name: sweet-shop-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sweet-shop-db
          property: connectionString

databases:
  - name: sweet-shop-db
    databaseName: sweetshop
    user: sweetshop
    plan: free
